# Generated by Django 3.2.5 on 2021-08-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_preco'),
        ('pedido', '0002_auto_20210819_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='preco',
            new_name='detalhes',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pag',
            field=models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Débito'), ('3', 'Crédito')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='item.Item'),
        ),
    ]
