# Generated by Django 3.2.6 on 2021-08-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_loja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionários'},
        ),
    ]
